### ISSUE TITLE
Plugin doesn't work with an exported project with minify option enabled

### ISSUE THREAD

**Issue by paala** [GameAnalytics/GA-SDK-CONSTRUCT#3]
The game shows only a black screen if you use the plugin and tick minify project.
without minify option enabled it works ok

**Comment by paala** [comment]
I had the same problem. Please check out here:
https://www.scirra.com/forum/plugin-works-in-preview-not-works-in-exported-game_t189165

**Comment by the1schwartz** [comment]
Thanks. We will look into it and fix it. Please use support from now on http://support.gameanalytics.com/hc/en-us/requests/new. We will close issues section now.
